### PR TITLE
Mobile menu

### PR DESCRIPTION
**Pull request by SulimanJoya**
## Changes
- Update the navigation bar in the index.html file
- Update the navigation bar style in the styles.css file
- Add a JavaScript file called script.js
- Linked the script.js to the index.html file

## Checklist before requesting a review
- [X] No linters error 
- [X] Followed the GitHub flow
- [X] documented professionally 
- [X] Followed the HTML and CSS best practices 
- [X] Followed the JavaScript best practices 
- [X] The mobile menu appears when the user clicks (or taps) the hamburger button.
- [X] When the user clicks (or taps) the close (X) button, the mobile menu disappears.
- [X] When the user clicks (or taps) any of the mobile menu options, the mobile menu disappears.
- [X] When the user clicks (or taps) any of the mobile menu options, a correct part of the page is displayed.

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @SulimanJoya and @MNisarAli, kindly use the updated version  of the microverse [readme](https://github.com/microverseinc/readme-template) template for your readme, this is a requirement to get a review set up both [JavaScript](https://github.com/microverseinc/linters-config/tree/master/javascript) and [HTML&CSS](https://github.com/microverseinc/linters-config/tree/master/html-css) linters👍🏿

**Comment by prolajumokeoni** [comment]
Hi @Team

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have he updated microverse readme, kindly use the updated version of the microverse [readme](https://github.com/microverseinc/readme-template) template for your readme, this is a requirement to get a review set up both [JavaScript](https://github.com/microverseinc/linters-config/tree/master/javascript) and [HTML&CSS](https://github.com/microverseinc/linters-config/tree/master/html-css) linters👍🏿 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by mckent05 — COMMENTED** [review]
Hi @SulimanJoya, 

# STATUS: INVALID REQUEST ❌ ❌ 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have the right linter checks set up, please use the [Javascript](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md) and [HTML && CSS](https://github.com/microverseinc/linters-config/tree/master/html-css) linter. The Javascriopt linter is currently missing ❌ ❌ 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by SulimanJoya** [comment]
Capture
This is 
the JavaScript liner file

**Review by muneebulrehman — APPROVED** [review]
Hi @SulimanJoya , 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🥳
Congratulations! 🎉 

# Status: Approved✔️

## Highlights
- Proper linter setup
- Descriptive PR
- Working project.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
